---
title: "London street dust_initial analysis"
author: "Daniel Schillereff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


###Install and load packages
```{r}
library(tidyverse)
library(ggpubr)
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(reshape2)
library(scales)
library(gghalves)
library(ggdist)
library(dplyr)
library(knitr)    # for kable
library(kableExtra) # for styling the table

#And for spatial mapping
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggspatial)
#library(ggmap)


```


###Load the XRF data
```{r}
#setwd("C:\\Users\\Danie\\OneDrive - King's College London\\London Street Dust\\XRF results")
setwd("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\XRF results")

xrf1 <- read.csv("Londonstreetdust_xrf_25.09.2025.csv")


```

###Group 1, Priority elements: Cd, Cu, Fe, Pb, Zn
```{r Summary table of concentrations}
xrf.1.long <- xrf1 %>% 
                  pivot_longer(cols = "Al":"Zr",
                               cols_vary = "slowest",
                               names_to = c("Element"),
                               values_to = "Concentration", 
                               values_drop_na = TRUE
                                )
Group1.elements <- c("Cd", "Cu", "Fe", "Pb", "Zn")

xrf.Group1.long <- xrf.1.long %>%
  filter(Element %in% Group1.elements) %>%
  filter(!is.na(Concentration))

# Function to calculate geometric mean safely (ignores zeros or negatives)
geo_mean <- function(x) {
  x <- x[x > 0]  # geometric mean only makes sense for positive values
  if(length(x) == 0) return(NA)
  exp(mean(log(x)))
}

#Create a table
summary_table <- xrf.Group1.long %>%
  group_by(Element) %>%
  summarise(
    'Arithmetic Mean' = round(mean(Concentration, na.rm = TRUE), 1),
    'Geometric Mean' = round(geo_mean(Concentration),1),
    Median = round(median(Concentration, na.rm = TRUE), 1),
    SD = round(sd(Concentration, na.rm = TRUE), 1),
    Range = paste0(round(min(Concentration, na.rm = TRUE),0), "–", round(max(Concentration, na.rm = TRUE), 0))
  ) %>% 
    ungroup()

table1 <- summary_table %>%
  kable(
    caption = "Summary statistics of element concentrations (mg/kg)",
    digits = 0,
    align = c("l", "r", "r", "r", "r", "r"),
  ) %>%
  kable_styling(
    full_width = FALSE,
    position = "center",
    bootstrap_options = c("striped", "hover", "condensed", "responsive")
  )


```


```{r Boxplots}
xrf.1.long <- xrf1 %>% 
                  pivot_longer(cols = "Al":"Zr",
                               cols_vary = "slowest",
                               names_to = c("Element"),
                               values_to = "Concentration", 
                               values_drop_na = TRUE
                                )
Group1.elements <- c("Cd", "Cu", "Fe", "Pb", "Zn")

xrf.Group1.long <- xrf.1.long %>%
  filter(Element %in% Group1.elements) %>%
  filter(!is.na(Concentration))

xrf.Group1.long %>%
  group_by(Element) %>%
  summarize(n = n(), n_na = sum(is.na(Concentration)), class_type = class(Concentration[1]))

xrf.Group1.long$Concentration <- as.numeric(xrf.Group1.long$Concentration)

#Plotting as horizontal lines
p1 <- ggplot(xrf.Group1.long, aes(x = 1, y = Concentration)) +
  geom_point(
    shape = 95,         # underscore-like horizontal line
    size = 50,           # adjust point size
    alpha = 0.2,        # transparency
    color = "darkgrey"
  ) +
  facet_wrap(~Element, nrow = 1, scales = "free_y") +
  theme_bw() +
  labs(
    x = NULL,
    y = "Concentration (mg/kg)"
  ) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )


#Now plotting as boxplots
p2 <- ggplot(xrf.Group1.long, aes(x = 1, y = Concentration)) +
  geom_boxplot(
    width = 0.3,        # narrow box
    outlier.shape = NA  # remove default outliers
  ) +
  geom_jitter(
    width = 0.05,       # horizontal jitter
    size = 2,
    alpha = 0.5,
    color = "darkgrey"
  ) +
  facet_wrap(~Element, nrow = 1, scales = "free_y") + # one row, free y-axis per element
  scale_y_continuous(n.breaks = 8, expand = expansion(mult = c(0.05, 0.05))) +  # more tick marks
  theme_bw() +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank()
  ) +
  labs(
    y = "Concentration (mg/kg)"
  )


```

```{r Boxplots with crustal averages plotted}
Wedepohl <- data.frame(
  Element = c("Cd", "Cu", "Fe", "Pb", "Zn"),
  thresh = c(NA, 14.3, 30890, 17, 52)  # example values
)

TaylorMcLennan <- data.frame(
  Element = c("Cd", "Cu", "Fe", "Pb", "Zn"),
  thresh = c(NA, 25, (3.5*10000), 20, 71)  # example values
)

RudnickGao <- data.frame(
  Element = c("Cd", "Cu", "Fe", "Pb", "Zn"),
  thresh = c(NA, 28, (3.525 * 10000), 17, 67)  # example values
)

xrf.1.long <- xrf1 %>% 
                  pivot_longer(cols = "Al":"Zr",
                               cols_vary = "slowest",
                               names_to = c("Element"),
                               values_to = "Concentration", 
                               values_drop_na = TRUE
                                )
Group1.elements <- c("Cd", "Cu", "Fe", "Pb", "Zn")

xrf.Group1.long <- xrf.1.long %>%
  filter(Element %in% Group1.elements) %>%
  filter(!is.na(Concentration))

xrf.Group1.long %>%
  group_by(Element) %>%
  summarize(n = n(), n_na = sum(is.na(Concentration)), class_type = class(Concentration[1]))

xrf.Group1.long$Concentration <- as.numeric(xrf.Group1.long$Concentration)

#Plotting as horizontal lines
p1b <- ggplot(xrf.Group1.long, aes(x = 1, y = Concentration)) +
  geom_point(
    shape = 95,         # underscore-like horizontal line
    size = 50,           # adjust point size
    alpha = 0.2,        # transparency
    color = "darkgrey"
  ) +
   geom_hline(
    data = RudnickGao, 
    aes(yintercept = thresh),
    linetype = "dashed",
    color = "red"
  ) +
  facet_wrap(~Element, nrow = 1, scales = "free_y") +
  theme_bw() +
  labs(
    x = NULL,
    y = "Concentration (mg/kg)"
  ) +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )


#Now plotting as boxplots
p2b <- ggplot(xrf.Group1.long, aes(x = 1, y = Concentration)) +
  geom_boxplot(
    width = 0.3,        # narrow box
    outlier.shape = NA  # remove default outliers
  ) +
  geom_jitter(
    width = 0.05,       # horizontal jitter
    size = 2,
    alpha = 0.5,
    color = "darkgrey"
  ) +
  geom_hline(
    data = RudnickGao, 
    aes(yintercept = thresh),
    linetype = "dashed",
    color = "red"
  ) +
  facet_wrap(~Element, nrow = 1, scales = "free_y") + # one row, free y-axis per element
  scale_y_continuous(n.breaks = 8, expand = expansion(mult = c(0.05, 0.05))) +  # more tick marks
  theme_bw() +
  theme(
    strip.background = element_blank(),
    strip.text = element_text(face = "bold"),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank()
  ) +
  labs(
    y = "Concentration (mg/kg)"
  )


```

```{r Spatial plotting using OSM tiles}

sampleinfo1 <- read.csv("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\XRF results\\Londonstreetdust_sampleinfo.csv")

coords <- sampleinfo1 %>%
  select(Sample, Longitude, Latitude)

xrf_coords <- xrf.Group1.long %>%
  left_join(coords, by = "Sample")

xrf_coords_clean <- xrf_coords %>%
  filter(!is.na(Longitude) & !is.na(Latitude))

# Convert to sf object
xrf_sf <- st_as_sf(
  xrf_coords_clean,
  coords = c("Longitude", "Latitude"),  # column names in your CSV
  crs = 4326   # WGS84 (standard lat/long)
)

xrf_sf_pb <- xrf_sf %>% 
  filter(Element == "Pb")  # only Pb points

# Make sure coordinates are WGS84
xrf_sf_pb <- st_transform(xrf_sf_pb, 4326)

# Compute bounding box of Pb points
bbox <- st_bbox(xrf_sf_pb)

# Optionally expand slightly so points aren't on the edge
expand <- 0.01  # ~0.01 degrees ~ 1 km
xlim <- c(bbox["xmin"] - expand, bbox["xmax"] + expand)
ylim <- c(bbox["ymin"] - expand, bbox["ymax"] + expand)

#Produces a map of Pb overlaying London OSM. Takes a while to loads and too much amp clutter
Pbmap1 <- ggplot() +
  annotation_map_tile(type = "osm", zoom = 12) +  # only type and zoom
  geom_sf(data = xrf_sf_pb, aes(color = Concentration), size = 3) +
  coord_sf(xlim = xlim, ylim = ylim) +  # zoom to bounding box
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    title = "Sample Locations Colored by Pb Concentration",
    color = "Concentration (mg/kg)"
  )


#Using Stadia maps - this requires an API
# Get a Stamen tile
#london_map <- get_stadiamap(
#  bbox = c(left = -0.25, bottom = 51.45, right = 0.15, top = 51.60),
#  zoom = 12,
#  maptype = "stamen_terrain"
#)

```

```{r Now using natural earth basemap}
# Base map of UK (or Europe)
uk <- ne_countries(scale = "medium", country = "United Kingdom", returnclass = "sf")
rivers <- ne_download(scale = "medium", type = "rivers_lake_centerlines", category = "physical", returnclass = "sf")

# Plot Pb points
Pbmap2 <- ggplot() +
  geom_sf(data = uk, fill = "gray95", color = "gray80") +
  geom_sf(data = rivers, color = "blue") +
  geom_sf(data = xrf_sf_pb, aes(color = Concentration), size = 3) +
  coord_sf(xlim = c(-0.25, 0.15), ylim = c(51.45, 51.60)) +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(title = "Pb Concentrations in London", color = "Concentration (mg/kg)")


#Plotting over major roads
library(osmdata)

# Define London bounding box
bbox_london <- c(-0.25, 51.45, 0.15, 51.60)

# Get major roads and rivers
london_osm <- opq(bbox = bbox_london) %>%
  add_osm_feature(key = "highway", value = c("primary", "secondary")) %>%
  osmdata_sf()

roads <- london_osm$osm_lines

Pb_map_roads <- ggplot() +
  geom_sf(data = roads, color = "gray50") +
  geom_sf(data = xrf_sf_pb, aes(color = Concentration), size = 3) +
  scale_color_viridis_c(option = "plasma") +
  coord_sf(xlim = c(-0.25, 0.15), ylim = c(51.45, 51.60)) +
  theme_minimal() +
  labs(title = "Pb Concentrations with Major Roads", color = "Concentration (mg/kg)")


```

```{r Plotting Pb over Boroughs}
#Plotting over Boroughs
setwd("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\XRF results")

# Read borough shapefile (download from e.g., London DataStore)
london_boroughs <- st_read("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\London data\\Shapefiles\\statistical-gis-boundaries-london\\statistical-gis-boundaries-london\\ESRI\\London_Borough_Excluding_MHW.shp")


xrf_sf_pb <- st_transform(xrf_sf_pb, st_crs(london_boroughs)) #convert to BNG

london_bbox <- st_bbox(c(
  xmin = 508000, xmax = 551000,   # Easting (metres)
  ymin = 167000, ymax = 193000    # Northing (metres)
), crs = st_crs(london_boroughs))

london_points <- st_crop(xrf_sf_pb, london_bbox)
london_boroughs_crop <- st_crop(london_boroughs, london_bbox)

Pb_boroughs_allsamples <- ggplot() +
  geom_sf(data = london_boroughs_crop, fill = "gray95", color = "gray80") +
  geom_sf(data = london_points %>% filter(Element == "Pb"),
          aes(color = Concentration), size = 4, shape = 16) +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    title = "Pb Concentrations - all samples",
    color = "Concentration (mg/kg)"
  )

#Now plotting only samples where Pb < 1000 ppm
xrf_sf_pb_1000 <- xrf_sf %>%
  filter(Element == "Pb", Concentration <= 1000)

xrf_sf_pb_1000 <- st_transform(xrf_sf_pb_1000, st_crs(london_boroughs)) #convert to BNG

london_bbox <- st_bbox(c(
  xmin = 508000, xmax = 551000,   # Easting (metres)
  ymin = 167000, ymax = 193000    # Northing (metres)
), crs = st_crs(london_boroughs))

london_points_Pb <- st_crop(xrf_sf_pb_1000, london_bbox)
london_boroughs_crop <- st_crop(london_boroughs, london_bbox)

Pb_boroughs_1000ppm <- ggplot() +
  geom_sf(data = london_boroughs_crop, fill = "gray95", color = "gray80") +
  geom_sf(data = london_points_Pb,
          aes(color = Concentration), size = 4, shape = 16) +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    title = "Pb Concentrations < 1000 mg/kg",
    color = "Concentration (mg/kg)"
  )

#Now plotting as varying size
Pb_boroughs_1000ppm_size <- ggplot() +
  geom_sf(data = london_boroughs_crop, fill = "gray95", color = "gray80") +
  geom_sf(data = london_points_Pb,
    aes(size = Concentration),   # map size to concentration
    shape = 21,                  # filled circle
    fill = "black", 
    #color = "black", 
    alpha = 0.7
  ) +
  scale_size_continuous(range = c(2, 8)) +  # adjust min/max point sizes
  theme_minimal() +
  labs(
    title = "Pb Concentrations < 1000 mg/kg",
    size = "Concentration (mg/kg)"
  )




```

```{r Plotting all Group 1 elements as facets over Boroughs}
sampleinfo1 <- read.csv("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\XRF results\\Londonstreetdust_sampleinfo.csv")

coords <- sampleinfo1 %>%
  select(Sample, Longitude, Latitude)

xrf_coords <- xrf.Group1.long %>%
  left_join(coords, by = "Sample")

xrf_coords_clean <- xrf_coords %>%
  filter(!is.na(Longitude) & !is.na(Latitude))

# Convert to sf object
xrf_sf <- st_as_sf(
  xrf_coords_clean,
  coords = c("Longitude", "Latitude"),  # column names in your CSV
  crs = 4326   # WGS84 (standard lat/long)
)

#convert coordinate system to BNG
xrf_sf <- st_transform(xrf_sf, st_crs(london_boroughs))

london_bbox <- st_bbox(c(
  xmin = 508000, xmax = 551000,   # Easting (metres)
  ymin = 167000, ymax = 193000    # Northing (metres)
), crs = st_crs(london_boroughs))

london_points <- st_crop(xrf_sf, london_bbox)
london_boroughs_crop <- st_crop(london_boroughs, london_bbox)

#TRYING AS FACETS BUT TRICKY BECAUSE DIFFERENT SCALES
# Plot faceted map
Group1_boroughs <- ggplot() +
  geom_sf(data = london_boroughs, fill = "gray95", color = "gray80") +
  geom_sf(data = london_points,
    aes(size = Concentration),   # map size to concentration
    shape = 21,                  # filled circle
    fill = "black", 
    color = "black", 
    alpha = 0.7
  ) +
  scale_size_continuous(range = c(2, 8)) +
  scale_color_viridis_c(option = "plasma") +
  facet_wrap(~Element) +
  theme_minimal() +
  labs(
    title = "XRF Sample Concentrations by Element",
    size = "Concentration (mg/kg)",
    color = "Concentration (mg/kg)"
  )




#WILL TRY IN A LOOP
Group1.elements <- c("Cd", "Cu", "Fe", "Pb", "Zn")

# Convert to sf object
xrf_sf <- st_as_sf(
  xrf_coords_clean,
  coords = c("Longitude", "Latitude"),  # column names in your CSV
  crs = 4326   # WGS84 (standard lat/long)
)

#convert coordinate system to BNG
xrf_sf <- st_transform(xrf_sf, st_crs(london_boroughs))

# Optional: remove rows with missing coordinates
xrf_sf_clean <- xrf_sf %>% filter(!is.na(geometry))

# Loop through each element and create a separate map
for (el in Group1.elements) {

  # Filter data for this element
  xrf_el <- xrf_sf %>% filter(Element == el)
  
  # Create the map
  p <- ggplot() +
    geom_sf(data = london_boroughs, fill = "gray95", color = "gray80") +
    geom_sf(
      data = xrf_el,
      aes(size = Concentration),   # map size to concentration
      shape = 21,                  # filled circle
      fill = "black", 
      color = "black", 
      alpha = 0.7
    ) +
    scale_size_continuous(range = c(1, 6)) +
    #scale_color_viridis_c(option = "plasma") +
    #coord_sf(
    #  xlim = c(-0.25, 0.15),  # approximate London longitudes
    #  ylim = c(51.45, 51.60)  # approximate London latitudes
    #) +
    theme_bw() +
    labs(
      title = paste("XRF Sample Concentrations of", el),
      size = "Concentration (mg/kg)",
      color = "Concentration (mg/kg)"
    )
  
  # Print the map
  print(p)
  
  # Optionally, save each map as a file
  # ggsave(filename = paste0("XRF_map_", el, ".png"), plot = p, width = 7, height = 6)
}

```


```{r}
# Read borough shapefile (download from e.g., London DataStore)
LAEI2022_pm10 <- st_read("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\London data\\Shapefiles\\LAEI2022-Emissions-Summary-GIS-Files\\Shapefile SHP\\LAEI2022-pm10-grid-emissions-all-sources.shp")

PM10_sf <- st_transform(LAEI2022_pm10, crs = st_crs(london_boroughs))
PM10_sf_clipped <- st_intersection(PM10_sf, london_boroughs)

Pb_PM10 <- ggplot() +
  geom_sf(data = london_boroughs, fill = "gray95", color = "black") +
  geom_sf(data = PM10_sf_clipped, aes(fill = all_2019), color = NA) +  geom_sf(data = london_points_Pb,
    aes(size = Concentration),   # map size to concentration
    shape = 21,                  # filled circle
    fill = "black", 
    color = "black", 
    alpha = 0.7
  ) +
  scale_size_continuous(range = c(1, 5)) +  # adjust min/max point sizes
  scale_fill_viridis_c(option = "plasma", name = "all_2019") +
  theme_bw() +
  labs(
    title = "Pb Concentrations - 2019 London Atmospheric Emissions Inventory LAEI",
    color = "Concentration (mg/kg)"
  )

# List all layers in the GeoPackage
layers <- st_layers("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\London data\\Shapefiles\\Locally_Significant_Industrial_Sites_LSIS.gpkg")

industrialsites_sf <- st_read("C:\\Users\\User\\OneDrive - King's College London\\London Street Dust\\London data\\Shapefiles\\Locally_Significant_Industrial_Sites_LSIS.gpkg", layer = "Locally_Significant_Industrial_Sites_LSIS")

# Convert Easting/Northing into an sf object
industrialsites_sf <- st_as_sf(industrialsites_sf,
                     coords = c("Easting", "Northing"),  # specify coordinate columns
                     crs = 27700)                        # example: British National Grid (OSGB36)

st_geometry(industrialsites_sf)
st_crs(industrialsites_sf) <- 27700
industrialsites_sf <- st_transform(industrialsites_sf, crs = st_crs(london_boroughs), options = "NO_GRIDSHIFT=YES")

#industrialsites_sf <- st_transform(industrialsites_sf, st_crs(london_boroughs)) #convert to BNG

london_bbox <- st_bbox(c(
  xmin = 508000, xmax = 551000,   # Easting (metres)
  ymin = 167000, ymax = 193000    # Northing (metres)
), crs = st_crs(london_boroughs))

london_points <- st_crop(xrf_sf_pb, london_bbox)
london_boroughs_crop <- st_crop(london_boroughs, london_bbox)
industrialsites_crop <- st_crop(industrialsites_sf, london_bbox)

Pb_boroughs_industrialsite_allsamples <- ggplot() +
  geom_sf(data = london_boroughs_crop, fill = "gray95", color = "gray80") +
  geom_sf(data = industrialsites_crop, fill = "red", color = "gray80") +
  geom_sf(data = london_points %>% filter(Element == "Pb"),
          aes(color = Concentration), size = 4, shape = 16) +
  scale_color_viridis_c(option = "plasma") +
  theme_minimal() +
  labs(
    title = "Pb Concentrations - all samples",
    color = "Concentration (mg/kg)"
  )


test111 <- ggplot() +
  geom_sf(data = london_boroughs, fill = "gray95", color = "black") +
  geom_sf(data = industrialsites_sf, fill = "red", color = "red", size = 1) +  geom_sf(data = london_points_Pb,
    aes(size = Concentration),   # map size to concentration
    shape = 21,                  # filled circle
    fill = "black", 
    color = "black", 
    alpha = 0.7
  ) +
  scale_size_continuous(range = c(1, 5)) +  # adjust min/max point sizes
  theme_bw() +
  labs(
    title = "Pb Concentrations - Locally Industrial Industrial Sites",
    color = "Concentration (mg/kg)"
  )
```



